# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  admin_name: Admin User
  admin_email: admin@app.com
  admin_password: password
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  db_user: root
  db_password: 5830056
  GOOGLE_OAUTH2_APP_ID: 84615955558-646r9j061qm6st9igctp1e21v83m42dv.apps.googleusercontent.com
  GOOGLE_OAUTH2_APP_SECRET: dMx4AaPWOkc1d5Vub9-_NJQ4
  FACEBOOK_APP_ID: 261425400930612
  FACEBOOK_APP_SECRET: 4729a764f11f3ddd09753b450d94e4f6
  secret_key_base: b553f5e0c3f91b9d72a57f8c79a645090c4aea84179248a05e84c4fbf9c487c409540e50799ff1caa1319bb1d3951512ceb56af3716fbb9615107e7ef1157b6b

test:
  db_user: root
  db_password: 5830056
  secret_key_base: 75e701e10957eea5458fd5f3242b04305115c511c6dc1d0823bd33d88083c1a7e60cf2f38190bc905d0a0e9dc61cde81bf95a721362748eaad80d50cadb3d22d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>